import { useState } from 'react'
import type { PlannedTripOption, TripPlanningResponse } from '@reel2route/contracts'
type Props={trip:TripPlanningResponse;onStartOver:()=>void}
const money=(amount:number,currency:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(amount/100)

function PlanDetails({option}:{option:PlannedTripOption}) {
  const tours=new Map(option.recommendations.map((item)=>[`${item.day}:${item.placeId}`,item.tours]))
  const stopCount=option.plan.days.reduce((total,day)=>total+day.stops.length,0)
  const coveredStops=option.recommendations.filter(({tours:matches})=>matches.length>0).length
  return <div className="result-layout"><section className="itinerary-panel"><div className="section-heading"><div><span className="eyebrow">Your route</span><h2>{option.plan.title}</h2></div><span className="bookability">Mock tour coverage: {coveredStops} of {stopCount}</span></div><p className="plan-summary">{option.plan.summary}</p>{stopCount<option.plan.days.length&&<p className="plan-summary"><strong>Source coverage:</strong> This {option.plan.days.length}-day request contains {stopCount} independently visitable source-backed {stopCount===1?'place':'places'}. Open days are kept honest rather than filled with invented stops.</p>}
    {option.plan.days.map((day)=><article className="day-card" key={day.day}><div className="day-header"><span>Day {day.day}</span><div><h3>{day.theme}</h3><p>{day.paceNote}</p></div></div><div className="timeline">{day.stops.map((stop)=><div className="stop" key={stop.placeId}><span className="stop-order">{stop.order}</span><div className="stop-content"><div className="stop-title"><div><h4>{stop.name}</h4><span>{stop.category} · {Math.round(stop.durationMinutes/6)/10}h</span></div><span className="confidence high">Source-backed</span></div><p>{stop.reason}</p><details className="evidence"><summary>Why we included this</summary>{stop.evidence.map((item,index)=><blockquote key={`${item.source}-${index}`}>“{item.text}” <span>— {item.source}{item.timestampSeconds===null?'':` at ${Math.round(item.timestampSeconds)}s`}</span></blockquote>)}</details>{(tours.get(`${day.day}:${stop.placeId}`)??[]).map((tour)=><div className="tour-card" key={tour.id}><div><span>{tour.includedInEstimate?'Included in estimate':'Alternative'} · Mock indicative price</span><strong>{tour.title}</strong><small>{tour.durationMinutes/60}h · ★ {tour.rating}</small></div><b>{money(tour.priceMinor,tour.currency)}</b></div>)}</div></div>)}{day.stops.length===0&&<p className="empty-day">Open day for rest, spontaneous finds, or travel.</p>}</div></article>)}
  </section><aside className="trip-sidebar"><section className="sidebar-card cost-card"><span className="eyebrow">Per person estimate</span><strong className="total-cost">{money(option.cost.totalPerPersonMinor,option.cost.currency)}</strong><span className="confidence low">Indicative estimate · not a live quote</span><div className="cost-lines">{option.cost.lineItems.map((item)=><div key={item.category}><span>{item.label}</span><b>{money(item.amountMinor,option.cost.currency)}</b></div>)}</div><details><summary>How this was estimated</summary><ul>{option.cost.lineItems.map((item)=><li key={item.category}><strong>{item.label}:</strong> {item.assumption}</li>)}{option.cost.assumptions.map((item)=><li key={item}>{item}</li>)}</ul></details></section><section className="sidebar-card"><span className="eyebrow">Pack light, move easy</span><h3>{option.packingSuggestion.luggage}</h3><p>{option.packingSuggestion.reason}</p><ul className="packing-list">{option.packingSuggestion.essentials.map((item)=><li key={item}>✓ {item}</li>)}</ul></section>{option.plan.unscheduledPlaces.length>0&&<section className="sidebar-card"><span className="eyebrow">Worth a second look</span><p>Unresolved or outside this plan’s pace.</p><div className="tag-list">{option.plan.unscheduledPlaces.map((place)=><span key={place}>{place}</span>)}</div></section>}</aside></div>
}

export function TripResults({trip,onStartOver}:Props) {
  const preferredPersona={budget:'budget_explorer',moderate:'comfort_traveller',premium:'premium_escape'}[trip.preferences.budgetRange]
  const initialSelection=Math.max(0,trip.options.findIndex(({plan})=>plan.persona.id===preferredPersona))
  const [selected,setSelected]=useState(initialSelection); const option=trip.options[selected]; const extraction=trip.analysis.extraction
  const contentLabel=trip.analysis.source.platform==='instagram'?'Reel':'video'
  const independentPlaces=extraction.places.filter(({role})=>role==='independent_place').length
  const resolvedPlaces=trip.analysis.resolvedPlaces.filter(({status})=>status==='resolved').length
  const unresolvedGaps=extraction.missingInformation.filter(({field})=>field!=='origin'&&field!=='trip_duration'&&field!=='transport_mode')
  if(independentPlaces===0)return <div className="results-view"><section className="results-hero"><div><span className="eyebrow">Limited {contentLabel.toLowerCase()} data</span><h1>{extraction.destinationGuess??`We need a richer ${contentLabel}`}</h1><p>{extraction.places.length} content mentions · 0 independently visitable · {resolvedPlaces} validated</p></div><button className="secondary-button" type="button" onClick={onStartOver}>Try another {contentLabel}</button></section><section className="insufficient-source" role="status"><span className="step-number">!</span><div><span className="eyebrow">Not enough evidence to build a route</span><h2>This {contentLabel.toLowerCase()} does not name any independently visitable places.</h2><p>We found only broad destination or contextual references. To keep the result evidence-backed, Reel2Route has not invented itinerary stops, tour matches, or a complete trip cost.</p><p><strong>Try content whose title, caption, description, or transcript names attractions, neighbourhoods, restaurants, hotels, or activities.</strong></p><button className="primary-button" type="button" onClick={onStartOver}>Choose richer content</button></div></section></div>
  const comparisonLabel=(personaId:PlannedTripOption['plan']['persona']['id'])=>{
    if(personaId===preferredPersona)return 'Best match'
    if(personaId==='budget_explorer')return 'Lower-cost alternative'
    if(personaId==='comfort_traveller')return trip.preferences.budgetRange==='budget'?'Comfort upgrade':'Balanced alternative'
    return 'Premium upgrade'
  }
  if(option===undefined)return null
  return <div className="results-view"><section className="results-hero"><div><span className="eyebrow">{contentLabel} decoded</span><h1>{extraction.destinationGuess??`Your ${contentLabel}-inspired trip`}</h1><p>{extraction.places.length} content mentions · {independentPlaces} independently visitable · {trip.analysis.resolvedPlaces.filter((place)=>place.status==='resolved').length} validated · {extraction.vibes.join(' · ')}</p></div><button className="secondary-button" type="button" onClick={onStartOver}>Plan another {contentLabel}</button></section>{extraction.missingInformation.length>0&&<section className="missing-banner"><span>!</span><div><strong>From {contentLabel} gaps to planning inputs</strong><p><b>Provided by you:</b> travelling from {trip.preferences.origin} for {trip.preferences.days} days · {trip.preferences.groupType} · {trip.preferences.pace} pace.</p><p><b>Applied by this plan:</b> {option.plan.persona.transportStyle}.</p>{unresolvedGaps.length>0&&<p><b>Still unknown:</b> {unresolvedGaps.map(({message})=>message).join(' ')}</p>}</div></section>}<div className="plan-tabs" role="tablist">{trip.options.map((item,index)=><button type="button" role="tab" aria-selected={selected===index} className={selected===index?'selected':''} onClick={()=>setSelected(index)} key={item.plan.persona.id}><span>Plan {String.fromCharCode(65+index)} · {comparisonLabel(item.plan.persona.id)}</span><strong>{item.plan.persona.name}</strong><small>{item.plan.persona.fitScore}% preference match · {money(item.cost.totalPerPersonMinor,item.cost.currency)}</small></button>)}</div><div className="persona-reason"><span>Why this plan fits</span><p>{option.plan.persona.reason}</p></div><PlanDetails option={option}/></div>
}
