import { useState } from 'react'
import type { PlannedTripOption, TripPlanningResponse } from '@reel2route/contracts'
type Props={trip:TripPlanningResponse;onStartOver:()=>void}
const money=(amount:number,currency:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(amount/100)

function PlanDetails({option}:{option:PlannedTripOption}) {
  const tours=new Map(option.recommendations.map((item)=>[`${item.day}:${item.placeId}`,item.tours]))
  return <div className="result-layout"><section className="itinerary-panel"><div className="section-heading"><div><span className="eyebrow">Your route</span><h2>{option.plan.title}</h2></div><span className="bookability">{option.bookabilityScore}% bookable</span></div><p className="plan-summary">{option.plan.summary}</p>
    {option.plan.days.map((day)=><article className="day-card" key={day.day}><div className="day-header"><span>Day {day.day}</span><div><h3>{day.theme}</h3><p>{day.paceNote}</p></div></div><div className="timeline">{day.stops.map((stop)=><div className="stop" key={stop.placeId}><span className="stop-order">{stop.order}</span><div className="stop-content"><div className="stop-title"><div><h4>{stop.name}</h4><span>{stop.category} · {Math.round(stop.durationMinutes/6)/10}h</span></div><span className="confidence high">Source-backed</span></div><p>{stop.reason}</p><details className="evidence"><summary>Why we included this</summary>{stop.evidence.map((item,index)=><blockquote key={`${item.source}-${index}`}>“{item.text}” <span>— {item.source}{item.timestampSeconds===null?'':` at ${Math.round(item.timestampSeconds)}s`}</span></blockquote>)}</details>{(tours.get(`${day.day}:${stop.placeId}`)??[]).map((tour)=><div className="tour-card" key={tour.id}><div><span>Mock tour match</span><strong>{tour.title}</strong><small>{tour.durationMinutes/60}h · ★ {tour.rating}</small></div><b>{money(tour.priceMinor,tour.currency)}</b></div>)}</div></div>)}{day.stops.length===0&&<p className="empty-day">Open day for rest, spontaneous finds, or travel.</p>}</div></article>)}
  </section><aside className="trip-sidebar"><section className="sidebar-card cost-card"><span className="eyebrow">Per person estimate</span><strong className="total-cost">{money(option.cost.totalPerPersonMinor,option.cost.currency)}</strong><span className="confidence low">Indicative estimate</span><div className="cost-lines">{option.cost.lineItems.map((item)=><div key={item.category}><span>{item.label}</span><b>{money(item.amountMinor,option.cost.currency)}</b></div>)}</div><details><summary>Cost assumptions</summary><ul>{option.cost.assumptions.map((item)=><li key={item}>{item}</li>)}</ul></details></section><section className="sidebar-card"><span className="eyebrow">Pack light, move easy</span><h3>{option.packingSuggestion.luggage}</h3><p>{option.packingSuggestion.reason}</p><ul className="packing-list">{option.packingSuggestion.essentials.map((item)=><li key={item}>✓ {item}</li>)}</ul></section>{option.plan.unscheduledPlaces.length>0&&<section className="sidebar-card"><span className="eyebrow">Worth a second look</span><p>Unresolved or outside this plan’s pace.</p><div className="tag-list">{option.plan.unscheduledPlaces.map((place)=><span key={place}>{place}</span>)}</div></section>}</aside></div>
}

export function TripResults({trip,onStartOver}:Props) {
  const [selected,setSelected]=useState(0); const option=trip.options[selected]; const extraction=trip.analysis.extraction
  if(option===undefined)return null
  return <div className="results-view"><section className="results-hero"><div><span className="eyebrow">Reel decoded</span><h1>{extraction.destinationGuess??'Your reel-inspired trip'}</h1><p>{extraction.places.length} places found · {trip.analysis.resolvedPlaces.filter((place)=>place.status==='resolved').length} validated · {extraction.vibes.join(' · ')}</p></div><button className="secondary-button" type="button" onClick={onStartOver}>Plan another reel</button></section>{extraction.missingInformation.length>0&&<section className="missing-banner"><span>!</span><div><strong>What the reel didn’t tell us</strong><p>{extraction.missingInformation.map(({message})=>message).join(' ')}</p></div></section>}<div className="plan-tabs" role="tablist">{trip.options.map((item,index)=><button type="button" role="tab" aria-selected={selected===index} className={selected===index?'selected':''} onClick={()=>setSelected(index)} key={item.plan.persona.id}><span>Plan {String.fromCharCode(65+index)}</span><strong>{item.plan.persona.name}</strong><small>{item.plan.persona.fitScore}% fit · {money(item.cost.totalPerPersonMinor,item.cost.currency)}</small></button>)}</div><div className="persona-reason"><span>Why this plan fits</span><p>{option.plan.persona.reason}</p></div><PlanDetails option={option}/></div>
}
